name: sirbituu
description: AI Music Studio Afaan Oromoof
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # Audio playback
  audioplayers: ^5.2.1

  # Audio recording
  record: ^5.0.4

  # Share files
  share_plus: ^7.2.2

  # Permissions
  permission_handler: ^11.0.1

  # File paths
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
